# Generated by Django 2.2.4 on 2020-05-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0003_auto_20200509_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('finish', 'Bitti'), ('list', 'Sırada'), ('read', 'Okunuyor')], default='general', max_length=8),
        ),
    ]
