# Generated by Django 2.2.4 on 2020-05-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0004_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('finish', 'Bitti'), ('list', 'Sırada'), ('read', 'Okunuyor')], default='list', max_length=8),
        ),
    ]
