# Generated by Django 2.2.4 on 2020-05-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0005_auto_20200509_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Trace',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
