# Generated by Django 2.2.4 on 2020-05-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0007_desktops_laptops_mobiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktops',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='desktops',
            name='price',
        ),
        migrations.RemoveField(
            model_name='desktops',
            name='status',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='price',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mobiles',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='mobiles',
            name='price',
        ),
        migrations.RemoveField(
            model_name='mobiles',
            name='status',
        ),
    ]
