# Generated by Django 2.2.4 on 2020-05-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0010_auto_20200509_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to='books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('finish', 'Bitti'), ('list', 'Okunuyor')], default='list', max_length=8),
        ),
    ]
