# Generated by Django 2.2.4 on 2020-05-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0012_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='type',
        ),
        migrations.RemoveField(
            model_name='trace',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trace',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trace',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='title_de',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='title_fr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='title_tr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='trace',
            name='title_de',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='trace',
            name='title_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='trace',
            name='title_fr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='trace',
            name='title_tr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
