# Generated by Django 2.2.4 on 2020-05-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0014_auto_20200518_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
