# Generated by Django 2.2.4 on 2020-05-18 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0017_auto_20200518_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lofd.Author'),
        ),
    ]
