# Generated by Django 2.2.4 on 2020-05-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0019_auto_20200518_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trace',
            new_name='Watching',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
    ]
