# Generated by Django 2.2.4 on 2020-05-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0020_auto_20200518_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watching',
            old_name='title_de',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='watching',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='watching',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='watching',
            name='title_tr',
        ),
    ]
