# Generated by Django 2.2.4 on 2020-05-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0022_bookadd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookadd',
            name='book',
        ),
        migrations.AddField(
            model_name='bookadd',
            name='book',
            field=models.ManyToManyField(to='lofd.Book'),
        ),
    ]
