# Generated by Django 2.2.4 on 2020-05-19 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0026_auto_20200518_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addwatch',
            name='items',
        ),
        migrations.AddField(
            model_name='addwatch',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lofd.Watching'),
        ),
    ]
