# Generated by Django 2.2.4 on 2020-05-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0027_auto_20200519_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addwatch',
            name='items',
        ),
        migrations.AddField(
            model_name='addwatch',
            name='items',
            field=models.ManyToManyField(to='lofd.Watching'),
        ),
    ]
