# Generated by Django 2.2.4 on 2020-05-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0028_auto_20200519_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddBook',
        ),
        migrations.DeleteModel(
            name='AddWatch',
        ),
    ]
