# Generated by Django 2.2.4 on 2020-05-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0030_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watch',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watch',
            field=models.ManyToManyField(to='lofd.Watching'),
        ),
    ]
