# Generated by Django 2.2.4 on 2020-05-20 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0031_auto_20200519_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watch',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lofd.Watching'),
        ),
    ]
