# Generated by Django 2.2.4 on 2020-05-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0032_auto_20200520_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watch',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watch',
            field=models.ManyToManyField(to='lofd.Watching', verbose_name='User List'),
        ),
    ]
