# Generated by Django 2.2.4 on 2020-05-20 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lofd', '0033_auto_20200520_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watch',
            field=models.ManyToManyField(blank=True, to='lofd.Watching'),
        ),
    ]
