# Generated by Django 2.2.4 on 2020-05-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0034_auto_20200520_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='movies')),
            ],
        ),
        migrations.RenameModel(
            old_name='Watching',
            new_name='Movie',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='watch',
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
