# Generated by Django 2.2.4 on 2020-05-20 17:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0037_liste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Zülfü LİVANELİ - SERANAD'), ('item_key2', 'Zülfü LİVANELİ - KARDEŞİMİN HİKAYESİ'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=49),
        ),
    ]
