# Generated by Django 2.2.4 on 2020-05-21 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lofd', '0038_auto_20200520_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(3, 'Ejderha Dövmeli Kız')], max_length=1),
        ),
        migrations.CreateModel(
            name='BookUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lofd.Book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
