# Generated by Django 2.2.4 on 2020-05-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0039_auto_20200521_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
    ]
