# Generated by Django 2.2.4 on 2020-05-21 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0040_auto_20200521_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookuserlist',
            name='booksList',
        ),
        migrations.AddField(
            model_name='bookuserlist',
            name='booksList',
            field=models.ManyToManyField(to='lofd.Book'),
        ),
        migrations.AlterField(
            model_name='bookuserlist',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
