# Generated by Django 2.2.4 on 2020-05-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0042_auto_20200521_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookuserlist',
            name='booksList',
        ),
        migrations.AddField(
            model_name='bookuserlist',
            name='booksList',
            field=models.ManyToManyField(to='lofd.Book'),
        ),
    ]
