# Generated by Django 2.2.4 on 2020-05-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0043_auto_20200521_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuserlist',
            name='booksList',
            field=models.ManyToManyField(blank=True, to='lofd.Book'),
        ),
    ]
