# Generated by Django 2.2.4 on 2020-05-24 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0046_auto_20200522_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='liste',
        ),
        migrations.AlterField(
            model_name='bookuserlist',
            name='booksList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lofd.Book'),
        ),
        migrations.AlterField(
            model_name='bookuserlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
