# Generated by Django 2.2.4 on 2020-05-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0048_book_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='movies')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
