# Generated by Django 2.2.4 on 2020-05-24 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lofd', '0049_auto_20200524_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watchesList', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lofd.Watch')),
            ],
        ),
    ]
