# Generated by Django 2.2.4 on 2020-05-24 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0052_auto_20200524_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='booksList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lofd.Book'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='watchesList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lofd.Watch'),
        ),
    ]
