# Generated by Django 2.2 on 2020-08-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0057_auto_20200815_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookuserlist',
            name='booksComments',
        ),
        migrations.AlterField(
            model_name='bookuserlist',
            name='booksList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lofd.Book'),
        ),
    ]
