# Generated by Django 2.2.13 on 2020-08-15 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0058_auto_20200815_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuserlist',
            name='booksList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lofd.Book'),
        ),
    ]
