# Generated by Django 2.2.13 on 2020-08-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0059_auto_20200815_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomment',
            name='booksList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lofd.Book'),
        ),
    ]
