# Generated by Django 2.2.13 on 2020-08-15 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0060_auto_20200815_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomment',
            name='booksList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lofd.Book'),
        ),
        migrations.AlterField(
            model_name='bookuserlist',
            name='booksList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lofd.Book'),
        ),
    ]
