# Generated by Django 2.2.13 on 2020-08-16 07:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0062_watchuserlist_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookuserlist',
            name='comments',
            field=ckeditor.fields.RichTextField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
