# Generated by Django 2.2.13 on 2020-08-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0063_bookuserlist_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuserlist',
            name='booksList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lofd.Book'),
        ),
    ]
