# Generated by Django 2.2.13 on 2020-08-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0065_auto_20200816_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookuserlist',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='watchuserlist',
            name='comments',
        ),
    ]
