# Generated by Django 2.2.13 on 2020-08-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0066_auto_20200816_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomment',
            name='booksList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lofd.Book'),
        ),
        migrations.AlterField(
            model_name='bookuserlist',
            name='booksList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lofd.Book'),
        ),
    ]
