# Generated by Django 2.2.13 on 2020-08-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0069_auto_20200823_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcomment',
            name='booksList',
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lofd.BookUserList'),
        ),
        migrations.AlterField(
            model_name='bookuserlist',
            name='booksList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booksList', to='lofd.Book'),
        ),
    ]
