# Generated by Django 2.2.13 on 2020-08-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lofd', '0070_auto_20200823_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcomment',
            old_name='user',
            new_name='p',
        ),
    ]
