# Generated by Django 2.2.13 on 2020-08-23 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lofd', '0072_auto_20200823_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeronalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('f_account', models.CharField(blank=True, max_length=200, null=True)),
                ('i_account', models.CharField(blank=True, max_length=200, null=True)),
                ('l_account', models.CharField(blank=True, max_length=200, null=True)),
                ('t_account', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
